# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - lf_hip_joint
    - lf_upper_leg_joint
    - lf_lower_leg_joint
    - lh_hip_joint
    - lh_upper_leg_joint
    - lh_lower_leg_joint
    - rf_hip_joint
    - rf_upper_leg_joint
    - rf_lower_leg_joint
    - rh_hip_joint
    - rh_upper_leg_joint
    - rh_lower_leg_joint
    - base_joint
    - lower_arm_joint
    - upper_arm_joint
    - wrist1_joint
    - wrist2_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []